POST  http://localhost:3333/auth/register
Content-Type: application/json

{
    "name": "Lucas Almeida",
    "cpf": "12345678910",
    "email": "lucas.almeida@example.com",
    "password": "senha1234",
    "user_type": "admin"
}


###

POST  http://localhost:3333/auth/login
Content-Type: application/json

{
    "cpf": "49312312312",
    "password": "123456"
}

###

POST  http://localhost:3333/create/demand
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiY3BmIjoiMjM5NTkxOTM5NzIiLCJpYXQiOjE3MjgwMDEwNTIsImV4cCI6MTcyODA4NzQ1Mn0.kX54v4-1B5Vj3sn1zybkNXTV0FIaFVc16X57lN1uR44

{
    "file_paths": "/raiz/2024_10_03",
    "status": "enviada"
}

###

GET  http://localhost:3333/demands
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiY3BmIjoiMTIzNDU2Nzg5MTAiLCJpYXQiOjE3MjgwMDYwMjksImV4cCI6MTcyODA5MjQyOX0.WXVUQWdyYRdCQ07fKB1yvwneNATNQXwt5RDSNM7uQ4A

###
PUT  http://localhost:3333/update/demand
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiY3BmIjoiMTIzNDU2Nzg5MTAiLCJpYXQiOjE3MjgwMDYwMjksImV4cCI6MTcyODA5MjQyOX0.WXVUQWdyYRdCQ07fKB1yvwneNATNQXwt5RDSNM7uQ4A

{
    "id": 1,
    "responsible_opinion": null,
    "file_paths": "/raiz/2024_10_03",
    "status": "cancelada",
    "aplicant": null
}

###

POST http://localhost:3333/upload

###
GET http://localhost:3333/download?file_paths=1_20241005_202837
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiY3BmIjoiNDkzMTIzMTIzMTIiLCJ1c2VyVHlwZSI6ImNvb3JkZW5hZG9yIiwibmFtZSI6Ik1hcmNlbG8gTWVuZXplcyAiLCJlbWFpbCI6Im1hcmNlbG9tZW5lemVzNTc1QGdtYWlsLmNvbSIsImlhdCI6MTcyODI2MzA4NSwiZXhwIjoxNzI4MzQ5NDg1fQ.EgeD1O3HO_3vZZ_BDFEmKm8qTC_6WVewVAd7Caax6G4

